/*
 * Quick Sort Implementation in C
 * Generated by ChatGPT (OpenAI)
 *
 * Description:
 * This program implements the Quick Sort algorithm to sort an integer array.
 * Quick Sort is a divide-and-conquer algorithm that selects a pivot element
 * and partitions the array into two subarrays according to the pivot.
 *
 * Author: ChatGPT
 */

#include <stdio.h>

// Swap two elements by reference
void swap(int *a, int *b) {
    int temp = *a;  // Store value of a
    *a = *b;        // Assign value of b to a
    *b = temp;      // Assign temp to b
}

// Partition function: places the pivot in the correct position
// and places all smaller elements to the left of pivot
// and all greater elements to the right
int partition(int arr[], int low, int high) {
    int pivot = arr[high];  // Choose last element as pivot
    int i = low - 1;        // Index of smaller element

    for (int j = low; j < high; j++) {
        // If current element is smaller than the pivot
        if (arr[j] < pivot) {
            i++;
            swap(&arr[i], &arr[j]);  // Swap elements
        }
    }

    // Place pivot in the correct position
    swap(&arr[i + 1], &arr[high]);
    return i + 1;  // Return pivot index
}

// Main Quick Sort function (recursive)
void quickSort(int arr[], int low, int high) {
    if (low < high) {
        // Partition the array and get pivot index
        int pi = partition(arr, low, high);

        // Recursively sort elements before and after partition
        quickSort(arr, low, pi - 1);
        quickSort(arr, pi + 1, high);
    }
}

// Utility function to print the array
void printArray(int arr[], int size) {
    for (int i = 0; i < size; i++)
        printf("%d ", arr[i]);
    printf("\n");
}

// Example usage
int main() {
    int arr[] = {10, 7, 8, 9, 1, 5};
    int n = sizeof(arr) / sizeof(arr[0]);

    quickSort(arr, 0, n - 1);  // Sort the array

    printf("Sorted array:\n");
    printArray(arr, n);        // Print sorted array

    return 0;
}